package com.devteam.tutorial.algorithms.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import javax.sql.XAConnection;

public class StudentDAO {
  private DbService dbService ;
  
  public StudentDAO(DbService dbService) {
    this.dbService = dbService;
  }
  
  public void createTable() throws SQLException {
    XAConnection conn = dbService.getConnection();
    String SQL = 
        "CREATE TABLE student(" +
            "  id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY," +
            "  firstName VARCHAR(255)," +
            "  lastName  VARCHAR(255)," +
            "  age       INT," +
            ")";
    Statement st =  conn.getConnection().createStatement();
    st.executeQuery(SQL);
    st.close();
    conn.close();
  }
  
  public Student retrieve(long studentId) throws SQLException {
    XAConnection conn = dbService.getConnection();
    String SQL = "SELECT id, firstName, lastName, age FROM student WHERE id = " + studentId ;
    Statement st =  conn.getConnection().createStatement();
    ResultSet resultSet = st.executeQuery(SQL);
    Student student = null;
    if(resultSet.next()) {
      student = retrieve(resultSet);
    }
    resultSet.close();
    st.close();
    conn.close();
    return student;
  }
  
  private Student retrieve(ResultSet rs) throws SQLException {
    Student student = new Student();
    student.setId(rs.getLong("id"));
    student.setFirstName(rs.getString("firstName"));
    student.setLastName(rs.getString("lastName"));
    student.setAge(rs.getInt("age"));
    return student;
  }
  
  public List<Student> retrieveByFirstName(String fName) throws SQLException {
    List<Student> holder = new ArrayList<>();
    XAConnection conn = dbService.getConnection();
    Statement st =  conn.getConnection().createStatement(); 
    String SQL = "SELECT id, firstName, lastName, age FROM student WHERE firstName = '" + fName + "'";
    ResultSet resultSet = st.executeQuery(SQL);
    while(resultSet.next()) {
      Student student = retrieve(resultSet);
      holder.add(student);
    }
    resultSet.close();
    conn.close();
    st.close();
    return holder;
  }
  
  public void insert(Student student)  throws SQLException {
    String SQL = "INSERT INTO student(firstName, lastName, age) VALUES (?, ?, ?)";
    XAConnection conn = dbService.getConnection();
    PreparedStatement p = conn.getConnection().prepareStatement(SQL);
    p.setString(1, student.getFirstName());
    p.setString(2, student.getLastName());
    p.setInt(3, student.getAge());
    p.execute();
    p.close();
    conn.close();
  }
  
  public void update(Student student)  throws SQLException {
    
  }
  
  public void remove(long studentId)  throws SQLException {
  }
  
  public int count()  throws SQLException {
    String SQL = "SELECT count(*) FROM student";
    XAConnection conn = dbService.getConnection();
    Statement st =  conn.getConnection().createStatement();
    ResultSet resultSet = st.executeQuery(SQL);
    resultSet.next();
    int count = resultSet.getInt(1);
    resultSet.close();
    st.close();
    conn.close();
    return count;
  }
}
